
# If we should deploy this kubernetes or not.  
# Setting this to false and re-running our deploy playbook will remove the kubernetes deployment 
# example to remove: ansible-playbook kubernetes/kube.deployment.playbook.yml --extra-vars '{deployment_enabled: false}'
deployment_enabled: true 

# Docker registry where this image will come from 
docker_registry: docker.io/library

service_configs:
  # Variabled specific to our app or service
  - name: nginx
    # Name of our container image within our registry 
    container_name: nginx
    # Tag of our image within our registry 
    container_tag: latest
    # Port exposed on kubernetes worker
    nodePort: 30080
    # Port exposed to the pod - note that nodePort is typically forwarded to this port
    port: 80

  - name: nginx2
    # Name of our container image within our registry 
    container_name: nginx
    # Tag of our image within our registry 
    container_tag: latest
    # Port exposed on kubernetes worker
    nodePort: 30081
    # Port exposed to the pod - note that nodePort is typically forwarded to this port
    port: 80

# A compiled variable of our image we will run in the pod  
# Note: this needs to be built outside of our our app: context due to a recursion bug in jinja2 
container_image: "{{docker_registry}}/{{app_service.container_name}}:{{app_service.container_tag}}"