---
- block:
    - name: set template encoding facts
      set_fact:
        cf_stack_template_yaml: "{{ cf_build_folder }}/{{ cf_stack_name }}-stack.yml"
        cf_stack_template_json: "{{ cf_build_folder }}/{{ cf_stack_name }}-stack.json"
        cf_stack_template_temp_json: "{{ cf_build_folder }}/{{ cf_stack_name }}-stack.tmp.json"
        cf_stack_policy_json: "{{ cf_build_folder }}/{{ cf_stack_name }}-policy.json"
        cf_stack_config_json: "{{ cf_build_folder }}/{{ cf_stack_name }}-config.json"

    - name: generator YAML template
      template:
        src: "{{ cf_stack_template }}"
        dest: "{{ cf_stack_template_yaml }}"
      changed_when: False

    - name: generator stack policy
      copy: content={{ cf_stack_policy | to_json }} dest={{ cf_stack_policy_json }}
      changed_when: False

    - name: set stack inputs
      set_fact:
        cf_stack_inputs: "{{ cf_stack_inputs | default(Stack.Inputs | default({})) }}"

    - debug: msg="inputs{{ cf_stack_inputs }}"

    - name: set stack config
      set_fact:
        cf_stack_config:
          Parameters: "{{ cf_stack_inputs }}"
          StackPolicy: "{{ cf_stack_policy }}"
          Tags: "{{ cf_stack_tags }}"

    - name: generator stack config
      copy: content={{ cf_stack_config | to_json }} dest={{ cf_stack_config_json }}
      changed_when: False
  tags:
    - generator

