---
# Add environment specific settings here

# aws-sts settings
# At a minimum you must specify the ARN of the IAM role
# that should be assumed to run your provisioning tasks
# e.g. Sts.Role: arn:aws:iam::012345678901:role/admin
# Sts.Role: <ARN of your IAM role>
Sts.Role: arn:aws:iam::236925568009:role/anisble-role
Sts.Region: 'ap-southeast-2'

# VPC Configuration
Config.Vpcs:
  Default:
    Cidr: 10.0.0.0/16
    Domain: microdevhub.org
    PublicSubnetsIpRanges:
      - 10.0.0.0/20
      - 10.0.16.0/20
    PrivateSubnetsIpRanges:
      - 10.0.32.0/20
      - 10.0.48.0/20