# The key difference is the scope of the variable.
# Variables defined in pre_tasks are limited to that section,
# while variables defined in vars are globally available to all tasks in the playbook.
---
- hosts: all
  gather_facts: yes
  vars:
    cf_stack_template: "{{ Stack.Template | default('./templates/base_resource.yml.j2') }}"
    cf_stack_name: "base-resource-{{ env }}"
    Stack:
      Inputs:
        Component: 'bookstore'

  pre_tasks:
    - name: create stack facts
      set_fact:
        tbd: "placeholder"

  roles:
    - role: assume_aws_role
    - role: cloudformation