---
- hosts: all
  gather_facts: yes
  vars:
    cf_stack_template: "{{ Stack.Template | default('./templates/eks.yml.j2') }}"
    cf_stack_name: "eks-resource-{{ env }}"

  roles:
    - role: assume_aws_role
    - role: cloudformation