---
- hosts: all
  gather_facts: yes
  vars_files:
    - ../catalog/apps/service.yml
  vars:
    namespace_name: "npr"
    kubeconfig_file: "~/.kube/config"
    deployment_file: "./templates/k8s_deployment.yml.j2"
    deployment_file_yml: "k8s_deployment.yml"

  roles:
    - role: assume_aws_role
    - role: k8s_deploy
