---
- hosts: all
  gather_facts: yes

  vars:
    kubeconfig_file: "~/.kube/config"
    deployment_file: "./templates/deployments/k8s_deployment.yml.j2"
    catalog_dir: "../catalog"

  tasks:
    - name: create stack variables
      set_fact:
        Stack: "{{ Stack | default({}) | combine((vars['hostvars'][env] | dotted_dict(paths=['Stack.'])).get('Stack') or {}, recursive=True) }}"

  roles:
    - role: assume_aws_role
    - role: k8s_deploy
