---
- hosts: all
  gather_facts: yes
  vars_files:
    - ../catalog/apps/service.yml
  vars:
    kubeconfig_file: "~/.kube/config"
    deployment_file: "./templates/k8s_deployment.yml.j2"
    manifest_app_dir: "../catalog/deployments/"
    # If we should deploy this kubernetes or not.  
    # Setting this to false and re-running our deploy playbook will remove the kubernetes deployment 
    deployment_enabled: true

  tasks:
    - name: create stack variables
      set_fact:
        Stack: "{{ Stack | default({}) | combine((vars['hostvars'][env] | dotted_dict(paths=['Stack.'])).get('Stack') or {}, recursive=True) }}"

  roles:
    - role: assume_aws_role
    - role: k8s_deploy
