---
- block:
  - name: install pre-requisites
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes 

  - name: Create a k8s namespace
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig_file }}"
      name: "{{ namespace_name }}"
      api_version: v1
      kind: Namespace
      state: present