- block:
    - import_tasks: init.yml
  when: deployment_enabled

- block:
  # Load service configurations
  - name: Load service configurations
    include_vars:
      file: "../catalog/apps/service.yml"
    no_log: true  # To avoid showing the content of the loaded variables in logs

  # Deploy services
  - name: Deploy Services
    include_tasks: roles/k8s_deploy/tasks/apply_deployment.yml
    loop: "{{ service_configs }}"
    loop_control:
      loop_var: app_service